import { ALL_PLAYWRIGHT_BROWSERS, type PlaywrightBrowser } from '../lib/playwright-browsers';
import { NOT_AVAILABLE } from '../lib/suite-origin';
import { CROSS_BROWSER_LIMITATIONS, type EngineVersionRow } from './versions';
import type { CrossBrowserFinding, CrossBrowserMatrixRow, EngineCellStatus } from './matrix';

function escapeCell(value: string): string {
  return value.replace(/\|/g, '\\|').replace(/\r?\n/g, '<br>');
}

function statusLabel(status: EngineCellStatus): string {
  return status;
}

function versionFor(engine: PlaywrightBrowser, versions: EngineVersionRow[]): string {
  return versions.find((row) => row.engine === engine)?.version ?? NOT_AVAILABLE;
}

export function renderCrossBrowserMatrixMarkdown(input: {
  target: string;
  passed: boolean;
  versions: EngineVersionRow[];
  playwrightVersion: string;
  rows: CrossBrowserMatrixRow[];
  findings: CrossBrowserFinding[];
  engineTotals: Record<
    PlaywrightBrowser,
    { total: number; passed: number; failed: number; skipped: number; notExecuted: number }
  >;
}): string {
  const engineSpecific = input.findings.filter((row) => row.kind === 'engine-specific-failure');
  const shared = input.findings.filter((row) => row.kind === 'shared-failure');
  const lines = [
    '# Cross-browser matrix',
    '',
    'Generated by `npm run test:e2e:cross-browser`.',
    '',
    '## Testing mode',
    '',
    'This run used Playwright **desktop engines** (`chromium`, `firefox`, `webkit`). It is **not a real device**. No real iOS Safari, real Android Chrome, or device-cloud session was executed.',
    '',
    ...CROSS_BROWSER_LIMITATIONS.map((line) => `- ${line}`),
    '',
    `Target: ${input.target}`,
    `Playwright: ${input.playwrightVersion}`,
    `Suite result: ${input.passed ? 'PASS' : 'FAIL'}`,
    '',
    '## Engines',
    '',
    '| Engine | Version | Real device | Passed | Failed | Skipped | Not executed |',
    '| --- | --- | --- | --- | --- | --- | --- |',
    ...ALL_PLAYWRIGHT_BROWSERS.map((engine) => {
      const totals = input.engineTotals[engine];
      return `| ${engine} | ${versionFor(engine, input.versions)} | no — Playwright desktop engine | ${totals.passed} | ${totals.failed} | ${totals.skipped} | ${totals.notExecuted} |`;
    }),
    '',
    '## Test × engine matrix',
    '',
    '| Test | Spec | Chromium | Firefox | WebKit | Engine-specific failure |',
    '| --- | --- | --- | --- | --- | --- |',
  ];

  if (input.rows.length === 0) {
    lines.push('| NOT_AVAILABLE | NOT_AVAILABLE | NOT_EXECUTED | NOT_EXECUTED | NOT_EXECUTED | no |', '');
  } else {
    for (const row of input.rows) {
      lines.push(
        `| ${escapeCell(row.title)} | ${escapeCell(row.specFile)} | ${statusLabel(row.cells.chromium.status)} | ${statusLabel(row.cells.firefox.status)} | ${statusLabel(row.cells.webkit.status)} | ${row.engineSpecificFailure ? 'yes' : 'no'} |`
      );
    }
    lines.push('');
  }

  lines.push(
    '## Browser-specific failures',
    '',
    'A finding is **browser-specific** when the same test passed on at least one engine and failed on another. Shared failures (all executed engines failed) are listed separately.',
    ''
  );

  if (engineSpecific.length === 0) {
    lines.push('No browser-specific failures were recorded.', '');
  } else {
    lines.push(
      '| Test | Spec | Failed engines | Passed engines | Failure | Screenshot | Trace |',
      '| --- | --- | --- | --- | --- | --- | --- |'
    );
    for (const row of engineSpecific) {
      lines.push(
        `| ${escapeCell(row.title)} | ${escapeCell(row.specFile)} | ${row.failedEngines.join(', ')} | ${row.passedEngines.join(', ') || NOT_AVAILABLE} | ${escapeCell(row.errorMessage)} | ${escapeCell(row.screenshotPath)} | ${escapeCell(row.tracePath)} |`
      );
    }
    lines.push('');
  }

  lines.push('## Shared failures (all executed engines)', '');
  if (shared.length === 0) {
    lines.push('No shared cross-engine failures were recorded.', '');
  } else {
    lines.push(
      '| Test | Spec | Engines | Failure | Screenshot | Trace | Video |',
      '| --- | --- | --- | --- | --- | --- | --- |'
    );
    for (const row of shared) {
      lines.push(
        `| ${escapeCell(row.title)} | ${escapeCell(row.specFile)} | ${row.failedEngines.join(', ')} | ${escapeCell(row.errorMessage)} | ${escapeCell(row.screenshotPath)} | ${escapeCell(row.tracePath)} | ${escapeCell(row.videoPath)} |`
      );
    }
    lines.push('');
  }

  return `${lines.join('\n')}\n`;
}
