import type { ContentFinding, ContentFindingStatus, ContentSummary } from './types';
import { CONTENT_DISCLAIMER, CONTENT_LIMITATIONS } from './types';

export interface ContentCounts {
  failCount: number;
  passCount: number;
  noteCount: number;
  warningCount: number;
  notTestedCount: number;
  blockedCount: number;
  bySeverity: ContentSummary['bySeverity'];
}

const EMPTY_SEVERITY: ContentSummary['bySeverity'] = { high: 0, medium: 0, low: 0, info: 0 };

export function tallyContentFindings(findings: ContentFinding[]): ContentCounts {
  const bySeverity = { ...EMPTY_SEVERITY };
  const counts: ContentCounts = {
    failCount: 0,
    passCount: 0,
    noteCount: 0,
    warningCount: 0,
    notTestedCount: 0,
    blockedCount: 0,
    bySeverity,
  };
  for (const row of findings) {
    bySeverity[row.severity] += 1;
    switch (row.status) {
      case 'FAIL':
        counts.failCount += 1;
        break;
      case 'PASS':
        counts.passCount += 1;
        break;
      case 'WARNING':
        counts.warningCount += 1;
        break;
      case 'NOTE':
      case 'NOT_APPLICABLE':
        counts.noteCount += 1;
        break;
      case 'NOT_TESTED':
        counts.notTestedCount += 1;
        break;
      case 'BLOCKED':
        counts.blockedCount += 1;
        break;
      default:
        break;
    }
  }
  return counts;
}

function escapeCell(value: string): string {
  return value.replace(/\|/g, '\\|').replace(/\r?\n/g, '<br>');
}

const STATUS_ORDER: ContentFindingStatus[] = [
  'FAIL',
  'BLOCKED',
  'WARNING',
  'NOTE',
  'NOT_TESTED',
  'NOT_APPLICABLE',
  'PASS',
];

export function renderContentFindingsMarkdown(summary: ContentSummary): string {
  const lines = [
    '# Content QA findings',
    '',
    'Generated by `npm run test:content`. Structural checks only — not factual verification of business claims.',
    '',
    `**${summary.disclaimer}**`,
    '',
    ...summary.limitations.map((line) => `- ${line}`),
    '',
    `Target: ${summary.target ?? 'NOT_AVAILABLE'}`,
    `Suite result: ${summary.passed ? 'PASS' : 'FAIL'}`,
    `Pages analyzed: ${summary.pagesAnalyzed}`,
    `PASS: ${summary.passCount} · FAIL: ${summary.failCount} · WARNING: ${summary.warningCount ?? 0} · NOTE/NOT_APPLICABLE: ${summary.noteCount} · NOT_TESTED: ${summary.notTestedCount ?? 0} · BLOCKED: ${summary.blockedCount ?? 0}`,
    '',
    '| Status | Severity | Rule | Page | Expected | Actual |',
    '| --- | --- | --- | --- | --- | --- |',
  ];

  const rows = [...summary.findings].sort(
    (a, b) => STATUS_ORDER.indexOf(a.status) - STATUS_ORDER.indexOf(b.status)
  );
  if (rows.length === 0) {
    lines.push('| NOTE | info | — | — | — | No findings were recorded |');
  } else {
    for (const row of rows) {
      lines.push(
        `| ${row.status} | ${row.severity} | ${escapeCell(row.rule)} | ${escapeCell(row.page)} | ${escapeCell(row.expected ?? '')} | ${escapeCell(row.actual ?? row.detail)} |`
      );
    }
  }
  lines.push('', '## Disclaimer', '', CONTENT_DISCLAIMER, '');
  return `${lines.join('\n')}\n`;
}

export { CONTENT_DISCLAIMER, CONTENT_LIMITATIONS };
