import fs from 'fs';
import path from 'path';
import { PATHS } from '../lib/paths';
import { logError, logStep, logSuccess, logWarn } from '../lib/logger';
import { resolveJmeterCommand } from '../lib/jmeter';
import { runCommand } from '../lib/run-command';
import { writeJson } from '../discovery/write-json';
import { gatePerformanceRun, isHeavyAuthorized } from '../performance/authorize';
import { evaluateThresholds, NOT_AVAILABLE, parseJmeterJtl } from '../performance/metrics';
import { normalizePerformanceProfile, resolvePerformanceProfile } from '../performance/profiles';
import type { PerformanceCli } from '../performance/cli';
import type { PerformanceRunStatus, PerformanceSummary } from '../performance/types';
import type { QaConfig } from '../types';

export interface RunJmeterOptions extends Partial<PerformanceCli> {}

function formatNumber(value: number | null | undefined, digits = 2): string {
  if (value == null || Number.isNaN(value)) return NOT_AVAILABLE;
  return Number.isInteger(value) ? String(value) : value.toFixed(digits);
}

function thresholdCell(summary: PerformanceSummary, metric: string): string {
  const row = summary.thresholds.comparisons.find((entry) => entry.metric === metric);
  if (!row) return NOT_AVAILABLE;
  if (row.status === 'NOT_AVAILABLE' || row.limit == null) return NOT_AVAILABLE;
  return `${row.limit} (${row.status})`;
}

function renderFindings(summary: PerformanceSummary): string {
  const metrics = summary.metrics;
  const lines = [
    '# Performance findings',
    '',
    'Generated by `npm run test:performance`. Measurements come from the JMeter JTL. Thresholds are never invented.',
    'Liveness profile status is RECORDED, never PASS. Core Web Vitals are not in this artifact — see reports/lighthouse/.',
    'Playwright UI page-load timings are not in this artifact — see reports/performance/.',
    'Plans live under tests/performance/jmeter/{smoke,load,stress,spike,soak}/. Heavy plans do not auto-run.',
    '',
    `- Profile: ${summary.profile}${summary.heavy ? ' (heavy — authorized only)' : ' (liveness)'}`,
    `- Run status: ${summary.status}`,
    `- Target: ${summary.target}`,
    `- Plan: ${summary.plan}`,
    `- Authorized: ${summary.authorized ? 'yes' : 'no'}`,
    `- Threshold status: ${summary.thresholds.status}`,
    '',
    summary.thresholds.note,
    '',
  ];

  if (summary.blocked) {
    lines.push(`BLOCKED: ${summary.blockReason}`, '');
  }
  if (summary.skipped) {
    lines.push(`NOT_EXECUTED: ${summary.skipReason}`, '');
  }

  if (metrics) {
    lines.push(
      '| Metric | Value | Threshold |',
      '| --- | --- | --- |',
      `| Request count | ${metrics.requestCount} | ${NOT_AVAILABLE} |`,
      `| Failures | ${metrics.failures} | ${NOT_AVAILABLE} |`,
      `| Successful | ${metrics.successful} | ${NOT_AVAILABLE} |`,
      `| Error rate | ${metrics.errorRatePercent.toFixed(2)}% | ${thresholdCell(summary, 'errorRatePercent')} |`,
      `| Average response time (ms) | ${metrics.avgMs} | ${thresholdCell(summary, 'avgMs')} |`,
      `| Minimum response time (ms) | ${metrics.minMs} | ${NOT_AVAILABLE} |`,
      `| Maximum response time (ms) | ${metrics.maxMs} | ${NOT_AVAILABLE} |`,
      `| p50 (ms) | ${formatNumber(metrics.p50Ms, 0)} | ${NOT_AVAILABLE} |`,
      `| p90 (ms) | ${formatNumber(metrics.p90Ms, 0)} | ${NOT_AVAILABLE} |`,
      `| p95 (ms) | ${formatNumber(metrics.p95Ms, 0)} | ${thresholdCell(summary, 'p95Ms')} |`,
      `| p99 (ms) | ${formatNumber(metrics.p99Ms, 0)} | ${NOT_AVAILABLE} |`,
      `| TTFB avg (ms) | ${formatNumber(metrics.ttfbMs, 0)} | ${NOT_AVAILABLE} |`,
      `| Throughput (requests/sec) | ${formatNumber(metrics.throughputPerSec)} | ${NOT_AVAILABLE} |`,
      `| Average latency (ms) | ${formatNumber(metrics.avgLatencyMs, 0)} | ${NOT_AVAILABLE} |`,
      `| Average connect (ms) | ${formatNumber(metrics.avgConnectMs, 0)} | ${NOT_AVAILABLE} |`,
      ''
    );
  }

  if (summary.samples.length > 0) {
    lines.push(
      '| # | Thread | Label | URL | Status | Elapsed (ms) | Result |',
      '| --- | --- | --- | --- | --- | --- | --- |'
    );
    summary.samples.forEach((sample, index) => {
      lines.push(
        `| ${index + 1} | ${sample.thread} | ${sample.label} | ${sample.url} | ${sample.responseCode ?? NOT_AVAILABLE} | ${formatNumber(sample.elapsedMs, 0)} | ${sample.success ? 'OK' : 'FAIL'} |`
      );
    });
    lines.push('');
  }

  return `${lines.join('\n')}\n`;
}

function resolveRunStatus(summary: Pick<PerformanceSummary, 'blocked' | 'skipped' | 'profile' | 'thresholds'>): PerformanceRunStatus {
  if (summary.blocked) return 'BLOCKED';
  if (summary.skipped) return 'NOT_EXECUTED';
  if (summary.profile === 'liveness') return 'RECORDED';
  return summary.thresholds.status;
}

function writeSummary(summary: PerformanceSummary): void {
  summary.status = resolveRunStatus(summary);
  fs.mkdirSync(PATHS.reports.jmeter, { recursive: true });
  writeJson(PATHS.jmeterSummary, summary);
  fs.writeFileSync(PATHS.jmeterFindings, renderFindings(summary), 'utf8');
}

function baseSummary(
  config: QaConfig,
  options: Required<Pick<PerformanceCli, 'profile' | 'authorizeHeavy'>>
): PerformanceSummary {
  const resolved = resolvePerformanceProfile(config, options.profile);
  return {
    ranAt: new Date().toISOString(),
    profile: resolved.id,
    status: 'NOT_EXECUTED',
    heavy: resolved.heavy,
    authorized: isHeavyAuthorized(options.profile, { authorizeHeavy: options.authorizeHeavy }),
    skipped: false,
    skipReason: null,
    blocked: false,
    blockReason: null,
    jmeterAvailable: Boolean(resolveJmeterCommand()),
    target: resolved.target,
    host: resolved.host,
    method: resolved.method,
    path: resolved.path,
    plan: path.relative(PATHS.root, resolved.planPath).replace(/\\/g, '/'),
    threads: resolved.threads,
    rampUpSeconds: resolved.rampUpSeconds,
    loopCount: resolved.loopCount,
    durationSeconds: resolved.durationSeconds ?? null,
    metrics: null,
    samples: [],
    thresholds: evaluateThresholds(null, config.jmeter.thresholds, resolved.id),
  };
}

export async function runJmeter(config: QaConfig, options: RunJmeterOptions = {}): Promise<boolean> {
  const profile = normalizePerformanceProfile(options.profile ?? config.jmeter.defaultProfile ?? 'liveness');
  const authorizeHeavy = Boolean(options.authorizeHeavy);
  const resolved = resolvePerformanceProfile(config, profile);

  if (!config.jmeter.enabled) {
    logWarn('JMeter step skipped (disabled in qa.config.json).');
    return true;
  }

  const summary = baseSummary(config, { profile, authorizeHeavy });
  const gate = gatePerformanceRun({
    profile,
    apiUrl: config.urls.api,
    authorizeHeavy,
    allowHeavyAgainst: config.jmeter.allowHeavyAgainst ?? [],
  });

  if (!gate.ok) {
    summary.blocked = true;
    summary.blockReason = gate.message;
    summary.authorized = gate.code !== 'NOT_AUTHORIZED';
    writeSummary(summary);
    logError(gate.message);
    return false;
  }

  const jmeterCommand = resolveJmeterCommand();
  if (!jmeterCommand) {
    summary.skipped = true;
    summary.jmeterAvailable = false;
    summary.skipReason =
      'JMeter not found. Install JMeter and add it to PATH, or set JMETER_HOME. No performance metrics were collected.';
    writeSummary(summary);
    logWarn(summary.skipReason);
    return true;
  }

  if (!fs.existsSync(resolved.planPath)) {
    logWarn(`JMeter plan missing at ${resolved.planPath} — run npm run qa:sync.`);
    summary.skipped = true;
    summary.skipReason = `JMeter plan not found: ${summary.plan}`;
    writeSummary(summary);
    return false;
  }

  logStep(`Performance tests (JMeter CLI) — ${profile} profile`);
  if (resolved.heavy) {
    logWarn(
      `Running authorized heavy profile "${profile}" against ${resolved.host}. This is not a CI default.`
    );
  }

  fs.mkdirSync(PATHS.reports.jmeter, { recursive: true });

  const resultFile = PATHS.jmeterResults;
  const htmlReportDir = path.join(PATHS.reports.jmeter, 'html');

  if (fs.existsSync(resultFile)) {
    fs.rmSync(resultFile, { force: true });
  }
  if (fs.existsSync(htmlReportDir)) {
    fs.rmSync(htmlReportDir, { recursive: true, force: true });
  }

  const result = runCommand(jmeterCommand, [
    '-n',
    '-t',
    resolved.planPath,
    '-l',
    resultFile,
    '-e',
    '-o',
    htmlReportDir,
  ]);

  const parsed = parseJmeterJtl(resultFile);
  summary.samples = parsed?.samples ?? [];
  summary.metrics = parsed?.metrics ?? null;
  summary.thresholds = evaluateThresholds(summary.metrics, config.jmeter.thresholds, profile);
  writeSummary(summary);

  if (summary.metrics) {
    const m = summary.metrics;
    logSuccess(
      `${profile}: ${m.requestCount} request(s), ${m.failures} failure(s), ` +
        `error rate ${m.errorRatePercent.toFixed(2)}%, avg ${m.avgMs} ms, ` +
        `p95 ${m.p95Ms == null ? NOT_AVAILABLE : `${m.p95Ms} ms`}, ` +
        `throughput ${m.throughputPerSec == null ? NOT_AVAILABLE : `${m.throughputPerSec.toFixed(2)}/s`}, ` +
        `status ${summary.status}, threshold ${summary.thresholds.status}`
    );
  } else {
    logWarn('JMeter finished without a parseable JTL — no metrics were fabricated.');
  }

  if (result.status === 0) {
    logSuccess(`JMeter ${profile} completed — report: ${htmlReportDir}`);
    if (summary.profile !== 'liveness' && summary.thresholds.status === 'breached') {
      logError('Configured performance thresholds were breached.');
      return false;
    }
    return true;
  }

  return false;
}
