import fs from 'fs';
import path from 'path';
import { PATHS } from '../lib/paths';
import { logError, logStep, logSuccess, logWarn } from '../lib/logger';
import { resolveJmeterCommand } from '../lib/jmeter';
import { runCommand } from '../lib/run-command';
import { writeJson } from '../discovery/write-json';
import { evaluateThresholds, NOT_AVAILABLE, parseJmeterJtl } from '../performance/metrics';
import {
  isLivenessProfile,
  resolvePerformanceProfile,
  type PerformanceProfileDecision,
  type ResolvedProfile,
} from '../performance/profiles';
import type { PerformanceCli } from '../performance/cli';
import type { PerformanceRunStatus, PerformanceSummary } from '../performance/types';
import { planInputFromConfig, renderJmeterPlan } from '../performance/jmx';
import { readLastTargetUrl } from '../lib/last-target';
import { resolveWebsiteTarget } from '../orchestrator/resolve-url';
import type { QaConfig } from '../types';

export interface RunJmeterOptions extends Partial<PerformanceCli> {}

function formatNumber(value: number | null | undefined, digits = 2): string {
  if (value == null || Number.isNaN(value)) return NOT_AVAILABLE;
  return Number.isInteger(value) ? String(value) : value.toFixed(digits);
}

function thresholdCell(summary: PerformanceSummary, metric: string): string {
  const row = summary.thresholds.comparisons.find((entry) => entry.metric === metric);
  if (!row) return NOT_AVAILABLE;
  if (row.status === 'NOT_AVAILABLE' || row.limit == null) return NOT_AVAILABLE;
  return `${row.limit} (${row.status})`;
}

function renderFindings(summary: PerformanceSummary): string {
  const metrics = summary.metrics;
  const lines = [
    '# Performance findings',
    '',
    'Generated by `npm run test:performance`. Measurements come from the JMeter JTL. Thresholds are never invented.',
    'Liveness profile status is RECORDED, never PASS. Core Web Vitals are not in this artifact — see reports/lighthouse/.',
    'Playwright UI page-load timings are not in this artifact — see reports/performance/.',
    'Plans live under tests/performance/jmeter/{smoke,load,stress,spike,soak}/. Heavy plans do not auto-run.',
    '',
    `- Profile: ${summary.profile}${summary.heavy ? ' (heavy — authorized only)' : ' (liveness)'}`,
    `- Run status: ${summary.status}`,
    `- Target: ${summary.target}${summary.targetSource === 'website' ? ' (website under test — no API URL configured)' : ''}`,
    `- Plan: ${summary.plan}`,
    `- Authorized: ${summary.authorized ? 'yes' : 'no'}`,
    `- Threshold status: ${summary.thresholds.status}`,
    '',
    summary.thresholds.note,
    '',
  ];

  if (summary.status === 'NOT_TESTED' && summary.skipReason) {
    lines.push(`NOT_TESTED: ${summary.skipReason}`, '');
  } else if (summary.status === 'REQUIRES_CONFIGURATION' && summary.blockReason) {
    lines.push(`REQUIRES_CONFIGURATION: ${summary.blockReason}`, '');
  } else if (summary.blocked) {
    lines.push(`BLOCKED: ${summary.blockReason}`, '');
  } else if (summary.skipped) {
    lines.push(`NOT_EXECUTED: ${summary.skipReason}`, '');
  }

  if (metrics) {
    lines.push(
      '| Metric | Value | Threshold |',
      '| --- | --- | --- |',
      `| Request count | ${metrics.requestCount} | ${NOT_AVAILABLE} |`,
      `| Failures | ${metrics.failures} | ${NOT_AVAILABLE} |`,
      `| Successful | ${metrics.successful} | ${NOT_AVAILABLE} |`,
      `| Error rate | ${metrics.errorRatePercent.toFixed(2)}% | ${thresholdCell(summary, 'errorRatePercent')} |`,
      `| Average response time (ms) | ${metrics.avgMs} | ${thresholdCell(summary, 'avgMs')} |`,
      `| Minimum response time (ms) | ${metrics.minMs} | ${NOT_AVAILABLE} |`,
      `| Maximum response time (ms) | ${metrics.maxMs} | ${NOT_AVAILABLE} |`,
      `| p50 (ms) | ${formatNumber(metrics.p50Ms, 0)} | ${NOT_AVAILABLE} |`,
      `| p90 (ms) | ${formatNumber(metrics.p90Ms, 0)} | ${NOT_AVAILABLE} |`,
      `| p95 (ms) | ${formatNumber(metrics.p95Ms, 0)} | ${thresholdCell(summary, 'p95Ms')} |`,
      `| p99 (ms) | ${formatNumber(metrics.p99Ms, 0)} | ${NOT_AVAILABLE} |`,
      `| TTFB avg (ms) | ${formatNumber(metrics.ttfbMs, 0)} | ${NOT_AVAILABLE} |`,
      `| Throughput (requests/sec) | ${formatNumber(metrics.throughputPerSec)} | ${NOT_AVAILABLE} |`,
      `| Average latency (ms) | ${formatNumber(metrics.avgLatencyMs, 0)} | ${NOT_AVAILABLE} |`,
      `| Average connect (ms) | ${formatNumber(metrics.avgConnectMs, 0)} | ${NOT_AVAILABLE} |`,
      ''
    );
  }

  if (summary.samples.length > 0) {
    lines.push(
      '| # | Thread | Label | URL | Status | Elapsed (ms) | Result |',
      '| --- | --- | --- | --- | --- | --- | --- |'
    );
    summary.samples.forEach((sample, index) => {
      lines.push(
        `| ${index + 1} | ${sample.thread} | ${sample.label} | ${sample.url} | ${sample.responseCode ?? NOT_AVAILABLE} | ${formatNumber(sample.elapsedMs, 0)} | ${sample.success ? 'OK' : 'FAIL'} |`
      );
    });
    lines.push('');
  }

  return `${lines.join('\n')}\n`;
}

function resolveRunStatus(
  summary: Pick<PerformanceSummary, 'blocked' | 'skipped' | 'profile' | 'thresholds' | 'status'>
): PerformanceRunStatus {
  if (summary.status === 'NOT_TESTED' || summary.status === 'REQUIRES_CONFIGURATION') {
    return summary.status;
  }
  if (summary.blocked) return 'BLOCKED';
  if (summary.skipped) return 'NOT_EXECUTED';
  if (isLivenessProfile(summary.profile)) return 'RECORDED';
  return summary.thresholds.status;
}

function writeSummary(summary: PerformanceSummary): void {
  summary.status = resolveRunStatus(summary);
  fs.mkdirSync(PATHS.reports.jmeter, { recursive: true });
  writeJson(PATHS.jmeterSummary, summary);
  fs.writeFileSync(PATHS.jmeterFindings, renderFindings(summary), 'utf8');
}

function emptySummaryShell(
  config: QaConfig,
  profileLabel: string,
  authorized: boolean,
  heavy: boolean,
  resolved: ResolvedProfile | null
): PerformanceSummary {
  return {
    ranAt: new Date().toISOString(),
    profile: resolved?.id ?? profileLabel,
    status: 'NOT_EXECUTED',
    heavy,
    authorized,
    skipped: false,
    skipReason: null,
    blocked: false,
    blockReason: null,
    jmeterAvailable: Boolean(resolveJmeterCommand()),
    targetSource: resolved?.targetSource,
    target: resolved?.target ?? config.jmeter.path,
    host: resolved?.host ?? '',
    method: resolved?.method ?? 'GET',
    path: resolved?.path ?? config.jmeter.path,
    plan: resolved
      ? path.relative(PATHS.root, resolved.planPath).replace(/\\/g, '/')
      : NOT_AVAILABLE,
    threads: resolved?.threads ?? 0,
    rampUpSeconds: resolved?.rampUpSeconds ?? 0,
    loopCount: resolved?.loopCount ?? 0,
    durationSeconds: resolved?.durationSeconds ?? null,
    metrics: null,
    samples: [],
    thresholds: evaluateThresholds(null, config.jmeter.thresholds, resolved?.id),
  };
}

function writeGateDecision(config: QaConfig, decision: Extract<PerformanceProfileDecision, { ok: false }>): void {
  const summary = emptySummaryShell(
    config,
    decision.requested,
    decision.authorized,
    decision.heavy,
    decision.resolved
  );
  summary.status = decision.status;
  if (decision.status === 'NOT_TESTED') {
    summary.skipped = true;
    summary.skipReason = decision.reason;
  } else if (decision.status === 'REQUIRES_CONFIGURATION') {
    summary.blocked = true;
    summary.blockReason = decision.reason;
  } else {
    summary.blocked = true;
    summary.blockReason = decision.reason;
  }
  writeSummary(summary);
}

export async function runJmeter(config: QaConfig, options: RunJmeterOptions = {}): Promise<boolean> {
  const requested = String(options.profile ?? config.jmeter.defaultProfile ?? 'liveness');
  const authorizeHeavy = Boolean(options.authorizeHeavy);

  if (!config.jmeter.enabled) {
    logWarn('JMeter step skipped (disabled in qa.config.json).');
    return true;
  }

  const websiteUrl = resolveWebsiteTarget({
    playwrightEnvUrl: process.env.QA_PLAYWRIGHT_BASE_URL,
    websiteEnvUrl: process.env.QA_WEBSITE_URL,
    lastTargetUrl: readLastTargetUrl(),
    playwrightBaseUrl: config.playwright.baseURL,
    websiteUrl: config.urls.website,
    environments: config.environments,
    activeEnvironment: config.environment?.active,
  });

  const decision = resolvePerformanceProfile(requested, config, { authorizeHeavy, websiteUrl });

  if (!decision.ok) {
    writeGateDecision(config, decision);
    if (decision.status === 'NOT_TESTED') {
      logWarn(`NOT_TESTED: ${decision.reason}`);
      return true;
    }
    logError(decision.reason);
    return false;
  }

  const resolved = decision.resolved;

  if (resolved.targetSource === 'website') {
    // No documented API URL: run the liveness plan against the website under test.
    // The static plan under tests/performance/jmeter/ stays API-only; write a runtime plan instead.
    const plan = planInputFromConfig(config, resolved.id);
    const runtimePlan = path.join(PATHS.reports.jmeter, 'website-liveness.jmx');
    fs.mkdirSync(PATHS.reports.jmeter, { recursive: true });
    fs.writeFileSync(
      runtimePlan,
      renderJmeterPlan({ ...plan, apiUrl: resolved.baseUrl, requestPath: resolved.path, targetKind: 'website' }),
      'utf8'
    );
    resolved.planPath = runtimePlan;
    logWarn(
      `No API URL configured — running JMeter liveness against the website under test: ${resolved.target}`
    );
  }

  const summary = emptySummaryShell(config, resolved.id, decision.authorized, resolved.heavy, resolved);

  const jmeterCommand = resolveJmeterCommand();
  if (!jmeterCommand) {
    summary.skipped = true;
    summary.jmeterAvailable = false;
    summary.skipReason =
      'JMeter not found. Install JMeter and add it to PATH, or set JMETER_HOME. No performance metrics were collected.';
    writeSummary(summary);
    logWarn(summary.skipReason);
    return true;
  }

  if (!fs.existsSync(resolved.planPath)) {
    logWarn(`JMeter plan missing at ${resolved.planPath} — run npm run qa:sync.`);
    summary.skipped = true;
    summary.skipReason = `JMeter plan not found: ${summary.plan}`;
    writeSummary(summary);
    return false;
  }

  logStep(`Performance tests (JMeter CLI) — ${resolved.id} profile`);
  if (resolved.heavy) {
    logWarn(
      `Running authorized heavy profile "${resolved.id}" against ${resolved.host}. This is not a CI default.`
    );
  }

  fs.mkdirSync(PATHS.reports.jmeter, { recursive: true });

  const resultFile = PATHS.jmeterResults;
  const htmlReportDir = path.join(PATHS.reports.jmeter, 'html');

  if (fs.existsSync(resultFile)) {
    fs.rmSync(resultFile, { force: true });
  }
  if (fs.existsSync(htmlReportDir)) {
    fs.rmSync(htmlReportDir, { recursive: true, force: true });
  }

  const result = runCommand(jmeterCommand, [
    '-n',
    '-t',
    resolved.planPath,
    '-l',
    resultFile,
    '-e',
    '-o',
    htmlReportDir,
  ]);

  const parsed = parseJmeterJtl(resultFile);
  summary.samples = parsed?.samples ?? [];
  summary.metrics = parsed?.metrics ?? null;
  summary.thresholds = evaluateThresholds(summary.metrics, config.jmeter.thresholds, resolved.id);
  writeSummary(summary);

  if (summary.metrics) {
    const m = summary.metrics;
    logSuccess(
      `${resolved.id}: ${m.requestCount} request(s), ${m.failures} failure(s), ` +
        `error rate ${m.errorRatePercent.toFixed(2)}%, avg ${m.avgMs} ms, ` +
        `p95 ${m.p95Ms == null ? NOT_AVAILABLE : `${m.p95Ms} ms`}, ` +
        `throughput ${m.throughputPerSec == null ? NOT_AVAILABLE : `${m.throughputPerSec.toFixed(2)}/s`}, ` +
        `status ${summary.status}, threshold ${summary.thresholds.status}`
    );
  } else {
    logWarn('JMeter finished without a parseable JTL — no metrics were fabricated.');
  }

  if (result.status === 0) {
    logSuccess(`JMeter ${resolved.id} completed — report: ${htmlReportDir}`);
    if (!isLivenessProfile(summary.profile) && summary.thresholds.status === 'breached') {
      logError('Configured performance thresholds were breached.');
      return false;
    }
    return true;
  }

  return false;
}
