import type { SeoFinding, SeoFindingStatus, SeoSuiteSummary } from './types';
import { SEO_DISCLAIMER, SEO_LIMITATIONS } from './types';

export interface SeoCounts {
  failCount: number;
  passCount: number;
  noteCount: number;
  warningCount: number;
  notTestedCount: number;
  blockedCount: number;
  bySeverity: NonNullable<SeoSuiteSummary['bySeverity']>;
}

const EMPTY_SEVERITY: NonNullable<SeoSuiteSummary['bySeverity']> = {
  high: 0,
  medium: 0,
  low: 0,
  info: 0,
};

function statusOf(row: SeoFinding): SeoFindingStatus {
  if (row.status) return row.status;
  if (row.severity === 'high') return 'FAIL';
  if (row.severity === 'medium') return 'WARNING';
  return 'NOTE';
}

export function tallySeoFindings(findings: SeoFinding[]): SeoCounts {
  const bySeverity = { ...EMPTY_SEVERITY };
  const counts: SeoCounts = {
    failCount: 0,
    passCount: 0,
    noteCount: 0,
    warningCount: 0,
    notTestedCount: 0,
    blockedCount: 0,
    bySeverity,
  };
  for (const row of findings) {
    bySeverity[row.severity] += 1;
    switch (statusOf(row)) {
      case 'FAIL':
        counts.failCount += 1;
        break;
      case 'PASS':
        counts.passCount += 1;
        break;
      case 'WARNING':
        counts.warningCount += 1;
        break;
      case 'NOTE':
      case 'NOT_APPLICABLE':
        counts.noteCount += 1;
        break;
      case 'NOT_TESTED':
        counts.notTestedCount += 1;
        break;
      case 'BLOCKED':
        counts.blockedCount += 1;
        break;
      default:
        break;
    }
  }
  return counts;
}

function escapeCell(value: string): string {
  return value.replace(/\|/g, '\\|').replace(/\r?\n/g, '<br>');
}

const STATUS_ORDER: SeoFindingStatus[] = [
  'FAIL',
  'BLOCKED',
  'WARNING',
  'NOTE',
  'NOT_TESTED',
  'NOT_APPLICABLE',
  'PASS',
];

export function renderSeoFindingsMarkdown(summary: SeoSuiteSummary): string {
  const lines = [
    '# SEO QA findings',
    '',
    'Generated by `npm run test:seo`. Technical SEO only — not a ranking audit.',
    '',
    `**${summary.disclaimer ?? SEO_DISCLAIMER}**`,
    '',
    ...(summary.limitations ?? SEO_LIMITATIONS).map((line) => `- ${line}`),
    '',
    `Target: ${summary.target ?? 'NOT_AVAILABLE'}`,
    `Suite result: ${summary.passed ? 'PASS' : 'FAIL'}`,
    `Pages analyzed: ${summary.pagesAnalyzed}`,
    `PASS: ${summary.passCount ?? 0} · FAIL: ${summary.failCount} · WARNING: ${summary.warningCount ?? 0} · NOTE/NOT_APPLICABLE: ${summary.noteCount ?? 0} · NOT_TESTED: ${summary.notTestedCount ?? 0} · BLOCKED: ${summary.blockedCount ?? 0}`,
    `Raw findings: ${summary.rawFindingCount} · Unique findings: ${summary.uniqueFindingCount}`,
    '',
    '| Status | Severity | Rule | Page | Expected | Actual |',
    '| --- | --- | --- | --- | --- | --- |',
  ];

  const rows = [...summary.findings].sort(
    (a, b) => STATUS_ORDER.indexOf(statusOf(a)) - STATUS_ORDER.indexOf(statusOf(b))
  );
  if (rows.length === 0) {
    lines.push('| NOTE | info | — | — | — | No findings were recorded |');
  } else {
    for (const row of rows) {
      lines.push(
        `| ${statusOf(row)} | ${row.severity} | ${escapeCell(row.rule)} | ${escapeCell(row.page)} | ${escapeCell(row.expected ?? '')} | ${escapeCell(row.actual ?? row.detail)} |`
      );
    }
  }
  lines.push('', '## Disclaimer', '', SEO_DISCLAIMER, '');
  return `${lines.join('\n')}\n`;
}

export { SEO_DISCLAIMER, SEO_LIMITATIONS };
