import fs from 'fs';
import path from 'path';
import { PATHS } from './lib/paths';
import { logError, logStep, logSuccess, logWarn } from './lib/logger';
import { runLocalBin } from './lib/run-command';
import { writeJson } from './discovery/write-json';
import { DEFAULT_FIXTURE_PORT, ensureFixtureChildProcess } from './testing/serve-fixture-site';
import { resolveUiTarget } from './lib/ui-target';
import { printCoverageSummary, runCoverage } from './coverage/run-coverage';
import { RESPONSIVE_LIMITATIONS, VIEWPORT_NAMES, VIEWPORTS } from './responsive/viewports';
import { planResponsiveChecks } from './responsive/applicability';
import type { ResponsiveFinding } from './responsive/findings';
import { loadConfig } from './lib/load-config';
import { QA_PLAYWRIGHT_SUITE_ENV, playwrightSuiteHtmlDir, playwrightSuiteResultsPath } from './lib/playwright-suites';
import { completePlaywrightSuite, preparePlaywrightSuite } from './lib/playwright-suite-summary';
import { resolveConfiguredPlaywrightBaseUrl } from './lib/suite-origin';

function loadFindings(): ResponsiveFinding[] {
  const dir = path.join(PATHS.root, 'test-results', 'responsive', 'findings');
  if (!fs.existsSync(dir)) return [];
  return fs
    .readdirSync(dir)
    .filter((name) => name.endsWith('.json'))
    .map((name) => JSON.parse(fs.readFileSync(path.join(dir, name), 'utf8')) as ResponsiveFinding);
}

function renderFindingsMarkdown(findings: ResponsiveFinding[]): string {
  const failures = findings.filter((row) => row.status === 'FAIL');
  const skipped = findings.filter((row) => row.status === 'NOT_APPLICABLE');
  const lines = [
    '# Responsive findings',
    '',
    'Generated by `npm run test:responsive`.',
    '',
    '## Testing mode',
    '',
    'This run used **emulated viewports** in Chromium (`page.setViewportSize` and Playwright project viewport/touch flags). It is **not a real device**. No real iOS Safari, real Android Chrome, or device-cloud session was executed.',
    '',
    ...RESPONSIVE_LIMITATIONS.map((line) => `- ${line}`),
    '',
    '## Emulated viewport matrix',
    '',
    '| Form factor | Size | Touch | Compact chrome | Real device |',
    '| --- | --- | --- | --- | --- |',
    ...VIEWPORT_NAMES.map((name) => {
      const profile = VIEWPORTS[name];
      return `| ${name} | ${profile.width}x${profile.height} | ${profile.hasTouch ? 'emulated' : 'no'} | ${profile.compactChrome ? 'yes' : 'no'} | no — emulated viewport |`;
    }),
    '',
    `Failures: ${failures.length}. Not applicable (pattern absent / not discovered — not invented): ${skipped.length}.`,
    '',
  ];

  if (failures.length === 0) {
    lines.push('No layout/functional responsive failures were recorded.', '');
  } else {
    lines.push(
      '## Failures',
      '',
      '| Page | Viewport | Affected element | Expected | Actual | Evidence |',
      '| --- | --- | --- | --- | --- | --- |'
    );
    for (const row of failures) {
      lines.push(
        `| ${row.page} (${row.pagePath}) | ${row.viewport} ${row.viewportSize} emulated viewport | ${row.affectedElement} | ${row.expected} | ${row.actual} | ${row.screenshot ?? ''} |`
      );
    }
    lines.push('');
  }

  if (skipped.length > 0) {
    lines.push(
      '## NOT_APPLICABLE (not invented)',
      '',
      '| Page | Viewport | Region | Reason |',
      '| --- | --- | --- | --- |'
    );
    for (const row of skipped) {
      lines.push(
        `| ${row.page} (${row.pagePath}) | ${row.viewport} emulated viewport | ${row.affectedElement} | ${row.actual} |`
      );
    }
    lines.push('');
  }

  return `${lines.join('\n')}\n`;
}

const RESPONSIVE_SKIPPED_BROWSERS = [
  { browser: 'firefox' as const, reason: 'responsive suite uses Chromium emulated viewports only — not a real device, not iOS Safari, not Android Chrome' },
  { browser: 'webkit' as const, reason: 'responsive suite uses Chromium emulated viewports only — not a real device, not Mobile Safari' },
];

async function main(): Promise<void> {
  const config = loadConfig();
  const target = resolveUiTarget(config);
  const started = preparePlaywrightSuite({
    suiteName: 'responsive',
    targetUrl: target.url,
    configuredBaseUrl: resolveConfiguredPlaywrightBaseUrl(),
  });
  const applicability = planResponsiveChecks();

  logStep('Responsive viewport matrix (Chromium emulated viewports — not a real device, not iOS Safari, not Android Chrome)');
  for (const line of RESPONSIVE_LIMITATIONS) {
    logWarn(line);
  }

  fs.mkdirSync(PATHS.reports.responsive, { recursive: true });
  fs.mkdirSync(path.join(PATHS.root, 'test-results', 'responsive'), { recursive: true });
  const findingsDir = path.join(PATHS.root, 'test-results', 'responsive', 'findings');
  fs.rmSync(findingsDir, { recursive: true, force: true });
  fs.mkdirSync(findingsDir, { recursive: true });

  runLocalBin('playwright', ['install', 'chromium']);

  let server: Awaited<ReturnType<typeof ensureFixtureChildProcess>> = null;
  if (target.isLoopback) {
    server = await ensureFixtureChildProcess(DEFAULT_FIXTURE_PORT);
    if (server) logSuccess(`Fixture site listening at ${server.url} (child process)`);
    else logWarn(`Fixture port ${DEFAULT_FIXTURE_PORT} already in use — assuming the responsive target is running`);
  } else {
    logStep(`Responsive suite target is live origin ${target.origin} — fixture site is not substituted`);
  }

  let passed = false;
  try {
    const result = runLocalBin(
      'playwright',
      ['test', `--config=${path.join(PATHS.root, 'playwright.responsive.config.ts')}`],
      {
        env: {
          ...process.env,
          QA_PLAYWRIGHT_BASE_URL: target.url,
          QA_PLAYWRIGHT_HEADLESS: process.env.QA_PLAYWRIGHT_HEADLESS ?? 'true',
          [QA_PLAYWRIGHT_SUITE_ENV]: 'responsive',
        },
      }
    );
    passed = result.status === 0;
  } finally {
    if (server) await server.close();
  }

  const findings = loadFindings();
  const failures = findings.filter((row) => row.status === 'FAIL');
  const notApplicable = findings.filter((row) => row.status === 'NOT_APPLICABLE');
  writeJson(path.join(PATHS.reports.responsive, 'applicability.json'), {
    generatedAt: new Date().toISOString(),
    target: target.url,
    testingMode: 'emulated viewport',
    realDeviceTesting: false,
    deviceCloud: false,
    checks: applicability,
  });
  writeJson(path.join(PATHS.reports.responsive, 'findings.json'), {
    generatedAt: new Date().toISOString(),
    target: target.url,
    testingMode: 'emulated viewport',
    realDeviceTesting: false,
    limitations: [...RESPONSIVE_LIMITATIONS],
    findings,
  });
  fs.writeFileSync(path.join(PATHS.reports.responsive, 'findings.md'), renderFindingsMarkdown(findings), 'utf8');
  const suiteSummary = completePlaywrightSuite(started, {
    passed,
    executedBrowsers: ['chromium'],
    skippedBrowsers: RESPONSIVE_SKIPPED_BROWSERS,
  });
  writeJson(path.join(PATHS.reports.responsive, 'summary.json'), {
    generatedAt: new Date().toISOString(),
    target: target.url,
    targetOrigin: suiteSummary.targetOrigin,
    originStatus: suiteSummary.originStatus,
    passed,
    failureCount: failures.length,
    notApplicableCount: notApplicable.length,
    testingMode: 'emulated viewport',
    realDeviceTesting: false,
    deviceCloud: false,
    engine: 'chromium',
    note: 'Emulated viewports only — not a real device. Visual may include a 375px login screenshot; this suite owns the desktop/laptop/tablet/mobile matrix and does not replace visual baselines.',
    viewports: VIEWPORT_NAMES.map((name) => ({
      name,
      width: VIEWPORTS[name].width,
      height: VIEWPORTS[name].height,
      hasTouch: VIEWPORTS[name].hasTouch,
      compactChrome: VIEWPORTS[name].compactChrome,
      realDevice: false,
      emulationNote: VIEWPORTS[name].emulationNote,
    })),
    applicability,
    applicableCount: applicability.filter((row) => row.status === 'APPLICABLE').length,
    plannedNotApplicableCount: applicability.filter((row) => row.status === 'NOT_APPLICABLE').length,
    resultsFile: playwrightSuiteResultsPath('responsive'),
    findingsFile: path.join(PATHS.reports.responsive, 'findings.json'),
    htmlReport: playwrightSuiteHtmlDir('responsive'),
    artifactsDir: path.join(PATHS.root, 'test-results', 'responsive'),
    limitations: [...RESPONSIVE_LIMITATIONS],
  });

  if (passed) logSuccess('Responsive viewport checks passed (emulated viewports only — not a real device)');
  else logError('Responsive checks failed — see reports/responsive/findings.md and test-results/responsive/evidence/');

  if (fs.existsSync(PATHS.pageMapFile) || fs.existsSync(playwrightSuiteResultsPath('responsive'))) {
    logStep('Updating coverage from responsive execution evidence');
    printCoverageSummary(runCoverage());
  }

  if (!passed) process.exit(1);
}

if (require.main === module) {
  main().catch((error: unknown) => {
    console.error(error);
    process.exit(1);
  });
}
