import fs from 'fs';
import path from 'path';
import { PATHS } from './lib/paths';
import { logError, logStep, logSuccess, logWarn } from './lib/logger';
import { runLocalBin } from './lib/run-command';
import { writeJson } from './discovery/write-json';
import { DEFAULT_FIXTURE_PORT, ensureFixtureChildProcess } from './testing/serve-fixture-site';
import { resolveUiTarget } from './lib/ui-target';
import { printCoverageSummary, runCoverage } from './coverage/run-coverage';
import { RESPONSIVE_LIMITATIONS } from './responsive/viewports';
import type { ResponsiveFinding } from './responsive/findings';
import { loadConfig } from './lib/load-config';
import { QA_PLAYWRIGHT_SUITE_ENV, playwrightSuiteHtmlDir, playwrightSuiteResultsPath } from './lib/playwright-suites';
import { completePlaywrightSuite, preparePlaywrightSuite } from './lib/playwright-suite-summary';

function loadFindings(): ResponsiveFinding[] {
  const dir = path.join(PATHS.root, 'test-results', 'responsive', 'findings');
  if (!fs.existsSync(dir)) return [];
  return fs
    .readdirSync(dir)
    .filter((name) => name.endsWith('.json'))
    .map((name) => JSON.parse(fs.readFileSync(path.join(dir, name), 'utf8')) as ResponsiveFinding);
}

function renderFindingsMarkdown(findings: ResponsiveFinding[]): string {
  const failures = findings.filter((row) => row.status === 'FAIL');
  const skipped = findings.filter((row) => row.status === 'NOT_APPLICABLE');
  const lines = [
    '# Responsive findings',
    '',
    'Generated by `npm run test:responsive`. Viewport projects are Chromium layout emulation.',
    '',
    ...RESPONSIVE_LIMITATIONS.map((line) => `- ${line}`),
    '',
    `Failures: ${failures.length}. Not applicable (pattern absent on that page): ${skipped.length}.`,
    '',
  ];

  if (failures.length === 0) {
    lines.push('No layout/functional responsive failures were recorded.', '');
  } else {
    lines.push(
      '| Page | Viewport | Affected element | Expected | Actual | Evidence |',
      '| --- | --- | --- | --- | --- | --- |'
    );
    for (const row of failures) {
      lines.push(
        `| ${row.page} (${row.pagePath}) | ${row.viewport} (${row.viewportSize}) | ${row.affectedElement} | ${row.expected} | ${row.actual} | ${row.screenshot ?? ''} |`
      );
    }
    lines.push('');
  }

  return `${lines.join('\n')}\n`;
}

const RESPONSIVE_SKIPPED_BROWSERS = [
  { browser: 'firefox' as const, reason: 'responsive suite uses Chromium viewport emulation only — not real devices or Mobile Safari' },
  { browser: 'webkit' as const, reason: 'responsive suite uses Chromium viewport emulation only — not real devices or Mobile Safari' },
];

async function main(): Promise<void> {
  const config = loadConfig();
  const target = resolveUiTarget(config);
  const started = preparePlaywrightSuite({
    suiteName: 'responsive',
    targetUrl: target.url,
    configuredBaseUrl: config.playwright.baseURL,
  });

  logStep('Responsive viewport matrix (Chromium emulation — not real devices, not Mobile Safari)');
  for (const line of RESPONSIVE_LIMITATIONS) {
    logWarn(line);
  }

  fs.mkdirSync(PATHS.reports.responsive, { recursive: true });
  fs.mkdirSync(path.join(PATHS.root, 'test-results', 'responsive'), { recursive: true });
  const findingsDir = path.join(PATHS.root, 'test-results', 'responsive', 'findings');
  fs.rmSync(findingsDir, { recursive: true, force: true });
  fs.mkdirSync(findingsDir, { recursive: true });

  runLocalBin('playwright', ['install', 'chromium']);

  let server: Awaited<ReturnType<typeof ensureFixtureChildProcess>> = null;
  if (target.isLoopback) {
    server = await ensureFixtureChildProcess(DEFAULT_FIXTURE_PORT);
    if (server) logSuccess(`Fixture site listening at ${server.url} (child process)`);
    else logWarn(`Fixture port ${DEFAULT_FIXTURE_PORT} already in use — assuming the responsive target is running`);
  } else {
    logStep(`Responsive suite target is live origin ${target.origin} — fixture site is not substituted`);
  }

  let passed = false;
  try {
    const result = runLocalBin(
      'playwright',
      ['test', `--config=${path.join(PATHS.root, 'playwright.responsive.config.ts')}`],
      {
        env: {
          ...process.env,
          QA_PLAYWRIGHT_BASE_URL: target.url,
          QA_PLAYWRIGHT_HEADLESS: process.env.QA_PLAYWRIGHT_HEADLESS ?? 'true',
          [QA_PLAYWRIGHT_SUITE_ENV]: 'responsive',
        },
      }
    );
    passed = result.status === 0;
  } finally {
    if (server) await server.close();
  }

  const findings = loadFindings();
  const failures = findings.filter((row) => row.status === 'FAIL');
  writeJson(path.join(PATHS.reports.responsive, 'findings.json'), {
    generatedAt: new Date().toISOString(),
    target: target.url,
    limitations: [...RESPONSIVE_LIMITATIONS],
    findings,
  });
  fs.writeFileSync(path.join(PATHS.reports.responsive, 'findings.md'), renderFindingsMarkdown(findings), 'utf8');
  const suiteSummary = completePlaywrightSuite(started, {
    passed,
    executedBrowsers: ['chromium'],
    skippedBrowsers: RESPONSIVE_SKIPPED_BROWSERS,
  });
  writeJson(path.join(PATHS.reports.responsive, 'summary.json'), {
    generatedAt: new Date().toISOString(),
    target: target.url,
    targetOrigin: suiteSummary.targetOrigin,
    originStatus: suiteSummary.originStatus,
    passed,
    failureCount: failures.length,
    notApplicableCount: findings.filter((row) => row.status === 'NOT_APPLICABLE').length,
    resultsFile: playwrightSuiteResultsPath('responsive'),
    findingsFile: path.join(PATHS.reports.responsive, 'findings.json'),
    htmlReport: playwrightSuiteHtmlDir('responsive'),
    artifactsDir: path.join(PATHS.root, 'test-results', 'responsive'),
    limitations: [...RESPONSIVE_LIMITATIONS],
  });

  if (passed) logSuccess('Responsive viewport checks passed (emulated viewports only)');
  else logError('Responsive checks failed — see reports/responsive/findings.md and test-results/responsive/evidence/');

  if (fs.existsSync(PATHS.pageMapFile) || fs.existsSync(playwrightSuiteResultsPath('responsive'))) {
    logStep('Updating coverage from responsive execution evidence');
    printCoverageSummary(runCoverage());
  }

  if (!passed) process.exit(1);
}

if (require.main === module) {
  main().catch((error: unknown) => {
    console.error(error);
    process.exit(1);
  });
}
